#!/bin/bash
# Reboot directly to Windows
# Inspired by http://askubuntu.com/questions/18170/how-to-reboot-into-windows-from-ubuntu
# https://unix.stackexchange.com/questions/43196/how-can-i-tell-grub-i-want-to-reboot-into-windows-before-i-reboot
start_windoes ()
{
    sudo windows_title=$(grep -i windows /boot/grub2/grub.cfg | cut -d "'" -f 2)
    sudo grub2-reboot "$windows_title" && sudo reboot
}
alias start_windows='start_win'
